### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by Tarang** [fastdatascience/faststylometry#2]
If i run the examples

```
from faststylometry.util import load_corpus_from_folder
from faststylometry.en import tokenise_remove_pronouns_en
from faststylometry.burrows_delta import calculate_burrows_delta

train_corpus = load_corpus_from_folder("faststylometry/data/train")

train_corpus.tokenise(tokenise_remove_pronouns_en)

test_corpus_sense_and_sensibility = load_corpus_from_folder("faststylometry/data/test", pattern="sense")

test_corpus_sense_and_sensibility.tokenise(tokenise_remove_pronouns_en)

calculate_burrows_delta(train_corpus, test_corpus_sense_and_sensibility)
```

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
[<ipython-input-3-6dc9c01c9a48>](https://ead5rh0oz7-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230214-060109-RC00_509470026#) in <module>
     11 test_corpus_sense_and_sensibility.tokenise(tokenise_remove_pronouns_en)
     12 
---> 13 calculate_burrows_delta(train_corpus, test_corpus_sense_and_sensibility)

1 frames
[/usr/local/lib/python3.8/dist-packages/faststylometry/burrows_delta.py](https://ead5rh0oz7-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230214-060109-RC00_509470026#) in get_top_tokens(corpus, vocab_size)
     17     """
     18 
---> 19     assert (len(corpus.tokens) > 0)  # you should have tokenised the corpus.
     20 
     21     token_freqs = Counter()

AssertionError:

The `train_corpus.tokenise(tokenise_remove_pronouns_en)` doesn't seem to do anything.

**Comment by Tarang** [comment]
Fyi this is on colab. But works locally.

**Comment by woodthom2** [comment]
@Tarang @06opoTeHb I apologise for the issue. It was due to a dependency on an old version of Pandas which was not correcltly indicated in the setup.py. I have updated the package. Please reinstall faststylometry version 1.0.1.

**Comment by jzsfvss** [comment]
I am still having the same issue. When I check train_corpus.top_tokens, it says no such attribute.

**Comment by woodthom2** [comment]
Hi József
Can you check you have all these dependencies in these exact versions?
Perhaps install it in a new venv/conda environment?

```
'numpy==1.24.3',
          'pandas==2.0.0',
          'scikit-learn==1.3.0',
          'nltk==3.7'
```
